스크립트 기여하기와 all contributors bot 적용 방법 추가
pythonkr/pyconkr-guide pull request #28
Opened 2020-03-15 04:43 UTC by golony6449

미뤄두었던 스크립트에 기여하는 방법, all-contributors 봇에 대한 내용을 추가했습니다.

`SUMMARY.md`에 추가는 했는데 이렇게 하면 적용되는 건지 모르겠습니다. ㅠㅠ

2020-03-15 05:27 UTC, emscb approved these changes
유튜브 링크가 빠졌어요.
오탈자 수정이 필요하지만 지금 제가 수정할 수 없기에 일단 머지 고고

2020-03-15 14:34 UTC, syohnet requested changes
잘 정리해주셔서 감사합니다. 링크 url에 대해 코멘트 드렸습니다.

2020-03-15 14:34 UTC, ohahohah commented on subtitles/03-merge.md
> + 파이콘 한국은 보다 많은 분들이 참여할 수 있는 행사가 되기위해 2018년 부터 문자통역을 제공하고 있습니다. 또한, 이때 만들어진 스크립트를 기반으로 [Youtube]()에 업로드된 발표영상에 자막으로 추가하는 작업을 진행중입니다.
https://www.youtube.com/channel/UC26x6D5xpKx6io4ShfXa_Ow 유튜브 링크 추가부탁드립니다.

2020-03-15 14:34 UTC, ohahohah commented on subtitles/03-merge.md
> +  *  [CoC](https://pycon.kr/2020/about/coc/)에 부적절한 내용은 없는지 확인해주세요. CoC에 위반한 내용이 있다면 `Reject` 될 수 있습니다.
홈페이지 구조에 따라 coc 링크는 변경될 수 있으니 https://github.com/pythonkr/pycon-code-of-conduct 이 링크로 변경 부탁드립니다.

2020-03-16 02:00 UTC, golony6449 commented on subtitles/03-merge.md
> +  *  [CoC](https://pycon.kr/2020/about/coc/)에 부적절한 내용은 없는지 확인해주세요. CoC에 위반한 내용이 있다면 `Reject` 될 수 있습니다.
앗 거기까지는 생각못했네요 ㅠㅠ 수정하겠습니다.

2020-03-16 02:03 UTC, merged