일하는 법/don't do 추가
pythonkr/pyconkr-guide pull request #8
Opened 2018-12-09 07:23 UTC by iiogmgo

don't do 는 머지 후 summary에 올릴 예정 (이전 pr과 충돌할거같음)

2018-12-09 07:46 UTC, iiogmgo commented on how-to-work/index.md
> +- 이 외에 CoC 담당자, 오락부장, 담당자의 담당장 등 다양한 역할을 추가하고있습니다.
담당장 오타

2018-12-09 07:46 UTC, iiogmgo commented on how-to-work/index.md
> +1. 온/오프를 막론하고 `회의록` 은 당일 작성이 아닌 전날 작성을 원칙으로 하며, 참석자들은 모두 *참석 전 회의록을 읽어오는 것을* 원칙으로 합니다. 이는 우리가 이야기 나눠야할 것들에 어떤 것이 있는지 같이 정리하고 확인하기 위함입니다. 또한 궁금한 점, 의견이 있는 점 등을 모두 문서에 자유롭게 적도록 합니다.
** 별이 두개여야함

2018-12-09 07:46 UTC, iiogmgo commented on how-to-work/index.md
> +사실상 도움이 되는 모든 일을 말합니다.
사실상 파이콘 한국 개최에 도움이 되는 모든 일을 말합니다.

2018-12-09 08:34 UTC, cmygray requested changes
오티때 신규 멤버분들께서 오해하셨던 부분들에 대한 자세한 설명을 추가하면 좋을 것 같습니다.

2018-12-09 08:34 UTC, cmygray commented on about/do-not-do.md
> +1. 외부 발표에서 발표 둘째페이지에 파이콘 한국 준비위원회를 기입하지 마세요.
1. 커뮤니티와 무관한 발표자료(예: 개발, 기술 컨퍼런스)에 파이콘 한국 준비위원회 소속임을 명시하지 마세요.

발표 둘째페이지 라는 설명이 다소 함축적이라 좀 더 자세히 설명하면 어떨까요

2018-12-09 08:34 UTC, cmygray commented on about/do-not-do.md
> +    - 준비위원회 활동에 대한 이력서 기입은 괜찮습니다.
> 파이콘 준비위원회로서 여러분은 개발, 디자인, 기획 등 여러가지 영역에서 기여하게 됩니다. 하지만 파이콘 한국 준비위원회는 여러분이 각 영역에서 어떤 사람인지 보증하지 않습니다. 여러분이 커뮤니티 활동과 무관한 컨퍼런스/세미나에서 파이콘 소속임을 밝히고 발표를 한다면 청중들은 "파이콘은 저렇게 개발, 디자인, 기획을 하는구나" 라고 오해할 수 있습니다. 이런 오해를 방지하기 위한 규칙으로, 소속을 밝히는 것은 발표가 좋고 나쁨과 상관없이 불필요합니다.

페이지 하단의 주석으로 링크하여 위 내용을 첨부하는 것은 어떨까요?

2018-12-09 08:34 UTC, cmygray commented on about/do-not-do.md
> +    - 하려면 모두에게 물어보고 하세요.
- 단, 모든 준비위원회의 동의 하에 진행하는 것은 괜찮습니다.

라고 하면 좀 더 부드러운 뉘앙스일 것 같아요.

2018-12-09 08:35 UTC, cmygray commented
@darjeeling 
"발표 둘째장" 관련 내용은 권한님도 한번 살펴봐주시면 좋겠어요

2018-12-10 05:29 UTC, darjeeling commented on about/do-not-do.md
> +    - 하려면 모두에게 물어보고 하세요.
@cmygray 동의합니다.

2018-12-10 05:35 UTC, darjeeling commented
장표 둘째장이라는 표현이 너무 모호함을 인정합니다. 설명을 길게 적기에는 무리일듯한데 음.. 어떻게할까요?

2018-12-13 10:10 UTC, iiogmgo commented
@darjeeling @cmygray 원님이 적어주신

커뮤니티와 무관한 발표자료(예: 개발, 기술 컨퍼런스)에 파이콘 한국 준비위원회 소속임을 명시하지 마세요.

로 충분할 것 같습니다.

2018-12-13 10:12 UTC, iiogmgo commented
@darjeeling @cmygray 리뷰해주신 부분들 반영해보았습니다 :)

2018-12-14 03:08 UTC, cmygray approved these changes

2018-12-14 03:08 UTC, cmygray commented
ready to merge

2018-12-17 04:56 UTC, merged